// This file is @generated by prost-build.
/// One CTRL frame on the OUT (host -> device) endpoint.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostToDevice {
    #[prost(oneof = "host_to_device::Msg", tags = "1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19")]
    pub msg: ::core::option::Option<host_to_device::Msg>,
}
/// Nested message and enum types in `HostToDevice`.
pub mod host_to_device {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Hello(super::Hello),
        #[prost(message, tag = "2")]
        Config(super::Config),
        #[prost(message, tag = "3")]
        OtaBegin(super::OtaBegin),
        #[prost(message, tag = "4")]
        OtaData(super::OtaData),
        #[prost(message, tag = "5")]
        OtaEnd(super::OtaEnd),
        #[prost(message, tag = "6")]
        OtaAbort(super::OtaAbort),
        #[prost(message, tag = "7")]
        AuthChallenge(super::AuthChallenge),
        /// Phase 2.
        #[prost(message, tag = "16")]
        GetDeviceInfo(super::GetDeviceInfo),
        #[prost(message, tag = "17")]
        SetParam(super::SetParam),
        #[prost(message, tag = "18")]
        Haptics(super::Haptics),
        #[prost(message, tag = "19")]
        Keepalive(super::Keepalive),
    }
}
/// One CTRL frame on the IN (device -> host) endpoint.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceToHost {
    #[prost(oneof = "device_to_host::Msg", tags = "1, 2, 3, 4, 5, 16, 17")]
    pub msg: ::core::option::Option<device_to_host::Msg>,
}
/// Nested message and enum types in `DeviceToHost`.
pub mod device_to_host {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        HelloAck(super::HelloAck),
        #[prost(message, tag = "2")]
        Touch(super::Touch),
        #[prost(message, tag = "3")]
        OtaStatus(super::OtaStatus),
        #[prost(message, tag = "4")]
        AuthResponse(super::AuthResponse),
        #[prost(message, tag = "5")]
        ConfigAck(super::ConfigAck),
        /// Phase 2.
        #[prost(message, tag = "16")]
        DeviceInfo(super::DeviceInfo),
        #[prost(message, tag = "17")]
        ParamAck(super::ParamAck),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hello {
    /// PV_PROTO_VERSION of the host.
    #[prost(uint32, tag = "1")]
    pub proto_version: u32,
}
/// Replaces the v1 packed caps bitfield with named flags.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Capabilities {
    #[prost(bool, tag = "1")]
    pub set_param: bool,
    /// Device has a DRV2605L haptic driver and answers Haptics messages.
    #[prost(bool, tag = "2")]
    pub haptics: bool,
    /// Device carries a vendor-provisioned identity and answers AuthChallenge.
    #[prost(bool, tag = "3")]
    pub auth: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HelloAck {
    #[prost(uint32, tag = "1")]
    pub proto_version: u32,
    #[prost(message, optional, tag = "2")]
    pub caps: ::core::option::Option<Capabilities>,
    #[prost(string, tag = "3")]
    pub fw_version: ::prost::alloc::string::String,
}
/// Resolved from the host's panel preset registry.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Config {
    #[prost(enumeration = "PanelModel", tag = "1")]
    pub model: i32,
    /// Visible size in pixels, in the panel's wired orientation.
    #[prost(uint32, tag = "2")]
    pub width: u32,
    #[prost(uint32, tag = "3")]
    pub height: u32,
    /// Glass insets into controller RAM.
    #[prost(uint32, tag = "4")]
    pub x_offset: u32,
    #[prost(uint32, tag = "5")]
    pub y_offset: u32,
    /// 0 / 90 / 180 / 270; drives MADCTL.
    #[prost(uint32, tag = "6")]
    pub rotation_deg: u32,
    #[prost(bool, tag = "7")]
    pub invert: bool,
    /// 7-bit I2C address of the touch controller; 0 disables touch.
    #[prost(uint32, tag = "8")]
    pub touch_addr: u32,
    /// Axis transforms the device applies before reporting touches.
    #[prost(bool, tag = "9")]
    pub touch_swap_xy: bool,
    #[prost(bool, tag = "10")]
    pub touch_flip_x: bool,
    #[prost(bool, tag = "11")]
    pub touch_flip_y: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConfigAck {
    #[prost(enumeration = "Status", tag = "1")]
    pub status: i32,
    /// Human-readable reason when status != OK (host logs it verbatim).
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
/// The firmware runs the down/move/up state machine and axis transforms; the
/// host forwards this to Dart untouched. (0,0) on UP.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Touch {
    #[prost(enumeration = "TouchPhase", tag = "1")]
    pub phase: i32,
    #[prost(uint32, tag = "2")]
    pub x: u32,
    #[prost(uint32, tag = "3")]
    pub y: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtaBegin {
    #[prost(uint32, tag = "1")]
    pub image_size: u32,
    /// SHA-256 of the full image; the device verifies before committing.
    #[prost(bytes = "vec", tag = "2")]
    pub sha256: ::prost::alloc::vec::Vec<u8>,
    /// esp_app_desc_t version extracted from the image (log-only on device).
    #[prost(string, tag = "3")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtaData {
    /// Chunk index, starting at 0 (detects drops on a desynced stream).
    #[prost(uint32, tag = "1")]
    pub seq: u32,
    /// Image bytes, at most 8192 per chunk (PV_OTA_CHUNK_MAX).
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtaEnd {}
/// Discard a partial transfer (host-side cancel).
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtaAbort {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtaStatus {
    #[prost(enumeration = "OtaState", tag = "1")]
    pub state: i32,
    /// Receive progress, 0–100.
    #[prost(uint32, tag = "2")]
    pub pct: u32,
    /// Device-side pv_ota_err code; 0 when state != FAILED.
    #[prost(sint32, tag = "3")]
    pub err: i32,
}
/// Liveness heartbeat. The host sends one at least every second while it holds
/// the link open.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Keepalive {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthChallenge {
    /// Fresh random nonce, exactly 32 bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthResponse {
    #[prost(enumeration = "AuthStatus", tag = "1")]
    pub status: i32,
    /// Opaque device certificate: version/device-id/issued-at/expires-at/device-
    /// pubkey + CA signature (pv_device_cert_t, 157 bytes). Its layout is its own
    /// versioned format keyed on cert\[0\] (cert_version), parsed at fixed offsets by
    /// the host's auth.rs, independent of this schema. The device key and the CA
    /// that signs the cert are both ECDSA P-256. Empty when status != OK.
    #[prost(bytes = "vec", tag = "2")]
    pub certificate: ::prost::alloc::vec::Vec<u8>,
    /// ECDSA P-256/SHA-256 signature over sha256("PVUS-ATTEST-V2" || nonce ||
    /// device_pubkey), a 64-byte r||s pair, produced by the device's eFuse ECDSA
    /// key via the on-chip ECDSA peripheral. Empty when status != OK.
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDeviceInfo {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PanelGeometry {
    #[prost(uint32, tag = "1")]
    pub width: u32,
    #[prost(uint32, tag = "2")]
    pub height: u32,
    #[prost(enumeration = "PanelShape", tag = "3")]
    pub shape: i32,
}
/// Lets the app select devices by serial and size its capture surface from the
/// device instead of the Dart-side kPicoViewModels table.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceInfo {
    /// Factory device id burned in at provisioning (e.g. "PV4-A00123").
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    /// USB serial string.
    #[prost(string, tag = "2")]
    pub serial: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub fw_version: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub proto_version: u32,
    #[prost(message, optional, tag = "5")]
    pub panel: ::core::option::Option<PanelGeometry>,
    #[prost(message, optional, tag = "6")]
    pub caps: ::core::option::Option<Capabilities>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetParam {
    #[prost(oneof = "set_param::Param", tags = "1")]
    pub param: ::core::option::Option<set_param::Param>,
}
/// Nested message and enum types in `SetParam`.
pub mod set_param {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Param {
        /// Backlight, 0 (off) – 255 (full).
        #[prost(uint32, tag = "1")]
        Brightness(u32),
    }
}
/// The device answers every SetParam with one of these. The host treats SetParam
/// as fire-and-forget (a UI slider may send them rapidly), so it logs the ack
/// rather than blocking on it — but the device must still send one.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParamAck {
    #[prost(enumeration = "Status", tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
}
/// Drive the panel's haptic actuator. Truly fire-and-forget: unlike SetParam
/// there is no ack message at all (a dropped UI buzz is harmless). `play`
/// triggers one ROM effect through the DRV2605L waveform sequencer; `stop`
/// clears a running effect.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Haptics {
    #[prost(oneof = "haptics::Cmd", tags = "1, 2")]
    pub cmd: ::core::option::Option<haptics::Cmd>,
}
/// Nested message and enum types in `Haptics`.
pub mod haptics {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Cmd {
        #[prost(message, tag = "1")]
        Play(super::HapticsPlay),
        #[prost(message, tag = "2")]
        Stop(super::HapticsStop),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HapticsPlay {
    /// ROM effect id, 1..123 (DRV2605L waveform library; see datasheet Table 12).
    /// 0 is not a valid effect and is ignored by the device.
    #[prost(uint32, tag = "1")]
    pub effect: u32,
    /// ROM library 1..7 to source the effect from; 0 keeps the firmware default
    /// (LRA library 6). Lets the host pick an ERM/LRA library without a rebuild.
    #[prost(uint32, tag = "2")]
    pub library: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HapticsStop {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Status {
    Unspecified = 0,
    Ok = 1,
    Error = 2,
    Unsupported = 3,
}
impl Status {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "STATUS_UNSPECIFIED",
            Self::Ok => "STATUS_OK",
            Self::Error => "STATUS_ERROR",
            Self::Unsupported => "STATUS_UNSUPPORTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "STATUS_OK" => Some(Self::Ok),
            "STATUS_ERROR" => Some(Self::Error),
            "STATUS_UNSUPPORTED" => Some(Self::Unsupported),
            _ => None,
        }
    }
}
/// Firmware-side display driver profile .
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PanelModel {
    Unspecified = 0,
    St77916 = 1,
    St7789 = 2,
}
impl PanelModel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PANEL_MODEL_UNSPECIFIED",
            Self::St77916 => "PANEL_MODEL_ST77916",
            Self::St7789 => "PANEL_MODEL_ST7789",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PANEL_MODEL_UNSPECIFIED" => Some(Self::Unspecified),
            "PANEL_MODEL_ST77916" => Some(Self::St77916),
            "PANEL_MODEL_ST7789" => Some(Self::St7789),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PanelShape {
    Unspecified = 0,
    Rect = 1,
    Round = 2,
}
impl PanelShape {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PANEL_SHAPE_UNSPECIFIED",
            Self::Rect => "PANEL_SHAPE_RECT",
            Self::Round => "PANEL_SHAPE_ROUND",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PANEL_SHAPE_UNSPECIFIED" => Some(Self::Unspecified),
            "PANEL_SHAPE_RECT" => Some(Self::Rect),
            "PANEL_SHAPE_ROUND" => Some(Self::Round),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TouchPhase {
    Unspecified = 0,
    Down = 1,
    Move = 2,
    Up = 3,
}
impl TouchPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TOUCH_PHASE_UNSPECIFIED",
            Self::Down => "TOUCH_PHASE_DOWN",
            Self::Move => "TOUCH_PHASE_MOVE",
            Self::Up => "TOUCH_PHASE_UP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TOUCH_PHASE_UNSPECIFIED" => Some(Self::Unspecified),
            "TOUCH_PHASE_DOWN" => Some(Self::Down),
            "TOUCH_PHASE_MOVE" => Some(Self::Move),
            "TOUCH_PHASE_UP" => Some(Self::Up),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OtaState {
    Unspecified = 0,
    Receiving = 1,
    Verifying = 2,
    Done = 3,
    Failed = 4,
}
impl OtaState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OTA_STATE_UNSPECIFIED",
            Self::Receiving => "OTA_STATE_RECEIVING",
            Self::Verifying => "OTA_STATE_VERIFYING",
            Self::Done => "OTA_STATE_DONE",
            Self::Failed => "OTA_STATE_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OTA_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "OTA_STATE_RECEIVING" => Some(Self::Receiving),
            "OTA_STATE_VERIFYING" => Some(Self::Verifying),
            "OTA_STATE_DONE" => Some(Self::Done),
            "OTA_STATE_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AuthStatus {
    Unspecified = 0,
    Ok = 1,
    /// Board with no vendor-provisioned identity (self-built, or a wiped devid).
    Unprovisioned = 2,
    SigningError = 3,
    MalformedChallenge = 4,
}
impl AuthStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AUTH_STATUS_UNSPECIFIED",
            Self::Ok => "AUTH_STATUS_OK",
            Self::Unprovisioned => "AUTH_STATUS_UNPROVISIONED",
            Self::SigningError => "AUTH_STATUS_SIGNING_ERROR",
            Self::MalformedChallenge => "AUTH_STATUS_MALFORMED_CHALLENGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUTH_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "AUTH_STATUS_OK" => Some(Self::Ok),
            "AUTH_STATUS_UNPROVISIONED" => Some(Self::Unprovisioned),
            "AUTH_STATUS_SIGNING_ERROR" => Some(Self::SigningError),
            "AUTH_STATUS_MALFORMED_CHALLENGE" => Some(Self::MalformedChallenge),
            _ => None,
        }
    }
}
