// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PvRequest {
    /// Correlation id, echoed on the matching PvResponse. Callers pick it (a
    /// per-controller counter is enough — the engine only ever hands it back).
    /// 0 means "no answer wanted": the request still runs, but nothing is posted.
    #[prost(uint32, tag = "1")]
    pub id: u32,
    /// How long the engine may spend before answering ERROR_CODE_TIMEOUT.
    /// 0 = the engine's default for this variant. Clamped to REQUEST_TIMEOUT_MAX.
    /// Only meaningful for the variants that round-trip (open_device,
    /// close_device, get_device_info); the rest answer immediately.
    #[prost(uint32, tag = "2")]
    pub timeout_ms: u32,
    #[prost(oneof = "pv_request::Req", tags = "3, 4, 5, 16, 17, 18")]
    pub req: ::core::option::Option<pv_request::Req>,
}
/// Nested message and enum types in `PvRequest`.
pub mod pv_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Req {
        #[prost(message, tag = "3")]
        OpenDevice(super::OpenDevice),
        #[prost(message, tag = "4")]
        CloseDevice(super::CloseDevice),
        #[prost(message, tag = "5")]
        OtaStart(super::OtaStart),
        /// Forwarded to the device.
        #[prost(message, tag = "16")]
        GetDeviceInfo(super::super::wire::GetDeviceInfo),
        #[prost(message, tag = "17")]
        SetParam(super::super::wire::SetParam),
        #[prost(message, tag = "18")]
        Haptics(super::super::wire::Haptics),
    }
}
/// Open the panel device and start a session. Round-trips: the `ack` is posted
/// once the device is open and the panel initialized (up to ~10s), or
/// ERROR_CODE_DEVICE when that fails, or ERROR_CODE_TIMEOUT if the worker did
/// not get to it in time. A LinkEvent(CONNECTED) is posted alongside the `ack`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenDevice {
    /// Nth enumerated device matching the pico-view VID/PID (ignored when `serial` is set).
    #[prost(uint32, tag = "1")]
    pub index: u32,
    /// Panel model preset name, e.g. "st77916-round-360"; empty = default.
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    /// Select by USB serial instead of index; empty = use index.
    #[prost(string, tag = "3")]
    pub serial: ::prost::alloc::string::String,
}
/// Stop the worker and close the device. Round-trips: the `ack` is posted after
/// teardown completes. Idempotent.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseDevice {}
/// Stream a signed ESP-IDF app image to the device and commit it. The `ack` is
/// posted as soon as the transfer is *enqueued*; progress and the result arrive
/// later as wire.OtaStatus events.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OtaStart {
    #[prost(bytes = "vec", tag = "1")]
    pub image: ::prost::alloc::vec::Vec<u8>,
}
/// The answer to one PvRequest, delivered as a PvEvent on the pv_init SendPort.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PvResponse {
    /// Echoes PvRequest.id, so the caller knows which request this answers.
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(oneof = "pv_response::Resp", tags = "2, 3, 4")]
    pub resp: ::core::option::Option<pv_response::Resp>,
}
/// Nested message and enum types in `PvResponse`.
pub mod pv_response {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Resp {
        #[prost(message, tag = "2")]
        Ack(super::Ack),
        #[prost(message, tag = "3")]
        Error(super::Error),
        #[prost(message, tag = "4")]
        DeviceInfo(super::super::wire::DeviceInfo),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ack {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(enumeration = "ErrorCode", tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Posted on transitions only (the worker de-duplicates).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LinkEvent {
    #[prost(enumeration = "LinkState", tag = "1")]
    pub state: i32,
    /// Reason for DISCONNECTED, for logs and the settings UI.
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
    /// Genuine-hardware result, meaningful only on CONNECTED: the device presented
    /// a valid vendor-CA-signed certificate and answered the attestation challenge.
    #[prost(bool, tag = "3")]
    pub verified: bool,
    /// The attested device id (from the certificate). Meaningful only when
    /// `verified`; empty otherwise.
    #[prost(string, tag = "4")]
    pub device_id: ::prost::alloc::string::String,
    /// The device's firmware version string (ESP-IDF app version, e.g. "1.4.0"),
    /// as reported in the HELLO_ACK handshake. Meaningful only on CONNECTED.
    #[prost(string, tag = "5")]
    pub fw_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PvEvent {
    #[prost(oneof = "pv_event::Event", tags = "1, 2, 3, 4")]
    pub event: ::core::option::Option<pv_event::Event>,
}
/// Nested message and enum types in `PvEvent`.
pub mod pv_event {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        Touch(super::super::wire::Touch),
        #[prost(message, tag = "2")]
        Link(super::LinkEvent),
        #[prost(message, tag = "3")]
        Ota(super::super::wire::OtaStatus),
        /// The answer to an earlier pv_request; match it on PvResponse.id.
        #[prost(message, tag = "4")]
        Response(super::PvResponse),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Unspecified = 0,
    /// Request decoded but is invalid (bad model name, empty image, ...).
    BadRequest = 1,
    /// open_device while a worker is running. Dart's hot-restart recovery relies
    /// on this being distinct: close_device, then retry the open once.
    AlreadyOpen = 2,
    /// Device-dependent request with no device open.
    NotOpen = 3,
    /// USB / device-setup failure.
    Device = 4,
    /// Worker queue gone (engine shutting down).
    Enqueue = 5,
    /// This engine build doesn't know the request variant.
    Unsupported = 6,
    Internal = 7,
    /// A request/reply command got no answer before its deadline.
    Timeout = 8,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ERROR_CODE_UNSPECIFIED",
            Self::BadRequest => "ERROR_CODE_BAD_REQUEST",
            Self::AlreadyOpen => "ERROR_CODE_ALREADY_OPEN",
            Self::NotOpen => "ERROR_CODE_NOT_OPEN",
            Self::Device => "ERROR_CODE_DEVICE",
            Self::Enqueue => "ERROR_CODE_ENQUEUE",
            Self::Unsupported => "ERROR_CODE_UNSUPPORTED",
            Self::Internal => "ERROR_CODE_INTERNAL",
            Self::Timeout => "ERROR_CODE_TIMEOUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERROR_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "ERROR_CODE_BAD_REQUEST" => Some(Self::BadRequest),
            "ERROR_CODE_ALREADY_OPEN" => Some(Self::AlreadyOpen),
            "ERROR_CODE_NOT_OPEN" => Some(Self::NotOpen),
            "ERROR_CODE_DEVICE" => Some(Self::Device),
            "ERROR_CODE_ENQUEUE" => Some(Self::Enqueue),
            "ERROR_CODE_UNSUPPORTED" => Some(Self::Unsupported),
            "ERROR_CODE_INTERNAL" => Some(Self::Internal),
            "ERROR_CODE_TIMEOUT" => Some(Self::Timeout),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LinkState {
    Unspecified = 0,
    /// Attached and configured.
    Connected = 1,
    /// Lost (unplug / OTA reboot); the engine reconnects on its own.
    Disconnected = 2,
}
impl LinkState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LINK_STATE_UNSPECIFIED",
            Self::Connected => "LINK_STATE_CONNECTED",
            Self::Disconnected => "LINK_STATE_DISCONNECTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LINK_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "LINK_STATE_CONNECTED" => Some(Self::Connected),
            "LINK_STATE_DISCONNECTED" => Some(Self::Disconnected),
            _ => None,
        }
    }
}
